### ISSUE TITLE
Error: Mop only supports Montage >=16.0.0.  This app has 0.15.2

### ISSUE THREAD

**Issue by damianoferrari** [montagejs/mop#65]
I am following the steps outlined in the "Hello MontageJS" tutorial. The app seems to be working fine, but when I try to run mop on it, I get this error:

Error: Mop only supports Montage >=16.0.0.  This app has 0.15.2

I just installed MontageJS today and created an app by following the directions in the tutorial:
- sudo npm install -gq minit@latest
- minit create:app -n <app name>
- cd <app name> && npm install

mop returns an error even if called on a newly created application, with no changes made to the code.

**Comment by marchant** [comment]
Damian, what version of montage is your project using right now? mop and montage versions need to be in lock steps and it looks like you're running the latest version of mop but the project is using montage 0.15.2. A simple fix should be to update the project to montage ~16.0.2

**Comment by marchant** [comment]
I just published mop v16.02 as there was a dependency in dev that should be there all the time, please update!

**Comment by lojosmit** [comment]
how does one update the version of montage, i tried that and it still fails.

{
    "name": "temp-converter",
    "version": "0.1.0",
    "dependencies": {
        "montage": "~16.0.3",
        "digit": "~0.5.1"
    },
    "devDependencies": {
        "montage-testing": "~0.4.0",
		"montage": "~16.0.3",
        "digit": "~0.5.1"
    },
    "exclude": [
        "run-tests.html",
        "test"
    ],
    "bundle": [ "ui/main.reel" ]
}

**Comment by hthetiot** [comment]
> npm uninstall montage digit --save
> npm install montage digit --save
> npm uninstall montage-testing --save-dev
> npm install montage-testing --save-dev

Or see updated temp-converter
https://github.com/montagejs/temp-converter
